### ISSUE TITLE
chromedriver.exe需要安装吗

### ISSUE THREAD

**Issue by BTUJACK** [weiensong/pond-loach#2]
chromedriver.exe需要安装吗

**Comment by touero** [comment]
需要安装的此项目获取数据部分基于selenium，请下载匹配自己电脑的chrome版本的chromedriver
请检查：https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json

然后修改路径：https://github.com/touero/pond-loach/blob/master/crawler.py#L26
